version: '3.9'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    networks:
      - app_network
    environment:
      - API_URL=http://api:5000
      - OLLAMA_URL=http://host.docker.internal:11434

  api_socketio: 
    build: ./api_socketio
    ports:
      - "5050:5050"
    networks:
      - app_network
    environment:
      - API_URL=http://api:5000
    depends_on:
      - api

  frontend:
    build: ./front
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - api  
      - api_socketio

networks:
  app_network: 
    driver: bridge